[package]
name = "wmata"
version = "0.1.0"
authors = ["stephen"]

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
reqwest = "0.8"
chrono =  { version = "0.4", features = ["serde"] }
failure = "0.1"